POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Mutia dilimeru arjayanti",
  "email": "rajeya@gmail.com",
  "password": "123",
  "confPassword": "123"
}

###
GET http://localhost:5000/users

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "rajeya@gmail.com",
  "password": "123"
}

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNdXRpYSBkaWxpbWVydSBhcmpheWFudGkiLCJlbWFpbCI6InJhamV5YUBnbWFpbC5jb20iLCJpYXQiOjE3MzA1MjE1OTcsImV4cCI6MTczMDUyMTYxMn0.fVG7z2KP_iWQ2MFu1Dh0tZQ1gsoOpwtfYb2qheDA0-s


###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout